"""add engine_power to scraped_cars

Revision ID: b9bace18d820
Revises: 5e7ef514a7bb
Create Date: 2026-03-14 09:59:29.566858
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bace18d820'
down_revision: Union[str, None] = '5e7ef514a7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_cars', sa.Column('engine_power', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_cars', 'engine_power')
    # ### end Alembic commands ###
